server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://${SPRING_CONFIG_USER}:${SPRING_CONFIG_PASS}@localhost:8888

  # Database Configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/dentistdss
    username: dentistdss
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true



eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false

# JWT Configuration
jwt:
  expiration: 86400000 # 24 hours in milliseconds
  rsa:
    private-key: ${JWT_RSA_PRIVATE_KEY:}
    public-key: ${JWT_RSA_PUBLIC_KEY:}
    key-id: ${JWT_RSA_KEY_ID:dentistdss}

# OpenAPI/SpringDoc Configuration - enabled for development
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    press.mizhifei.dentist: DEBUG
    org.springframework: DEBUG
    root: DEBUG

# App Configuration
app:
  email-verification:
    token-expiry-minutes: 43200 # 30 days in minutes
    code-expiry-minutes: 10 # 10 minutes in minutes
    base-url: ${BASE_URL:http://localhost:3000}