server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://zhifeimi:CSIT998CAPSTONE2025dentistdss@config-server:8888

  # Database Configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://postgres:5432/dentistdss
    username: dentistdss
    password: dentistdss
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true
