version: '3.8'

services:

  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: dentistdss
      POSTGRES_USER: dentistdss
      POSTGRES_PASSWORD: dentistdss
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - dentistdss-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dentistdss"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Config Server
  config-server:
    build:
      context: ./config-server
    container_name: config-server
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./config-server/src/main/resources/config:/app/config
    networks:
      - dentistdss-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ROOT=DEBUG

  # Discovery Server (Eureka)
  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - dentistdss-network
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://zhifeimi:CSIT998CAPSTONE2025dentistdss@config-server:8888

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "443:443"
    networks:
      - dentistdss-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://zhifeimi:CSIT998CAPSTONE2025dentistdss@config-server:8888
      - EUREKA_URI=http://discovery-server:8761/eureka

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8081:8081"
    networks:
      - dentistdss-network
    depends_on:
      - api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://zhifeimi:CSIT998CAPSTONE2025dentistdss@config-server:8888
      - EUREKA_URI=http://discovery-server:8761/eureka
      # - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dentistdss?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dentistdss

  # OAuth Service
  oauth-service:
    build:
      context: ./oauth-service
    container_name: oauth-service
    restart: always
    ports:
      - "8082:8082"
    networks:
      - dentistdss-network
    depends_on:
      - api-gateway
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CONFIG_IMPORT=optional:configserver:http://zhifeimi:CSIT998CAPSTONE2025dentistdss@config-server:8888
      - EUREKA_URI=http://discovery-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dentistdss
      # GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET should be managed by the config-server for docker profile

# Volumes
volumes:
  # mysql_data:
  #   driver: local
  postgres_data:
    driver: local

# Networks
networks:
  dentistdss-network:
    driver: bridge 