server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: false

spring:
  application:
    name: oauth-service
  config:
    import: optional:configserver:http://${SPRING_CONFIG_USER}:${SPRING_CONFIG_PASS}@config-server:8888

  # Database Configuration (PostgreSQL)
  datasource:
    url: jdbc:postgresql://postgres:5432/dentistdss
    username: dentistdss
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID} # To be overridden by config server
            client-secret: ${GOOGLE_CLIENT_SECRET} # To be overridden by config server
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" # Spring will resolve baseUrl
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub



# For Feign client to call auth-service
app:
  auth-service:
    url: http://auth-service:8081 # Use Docker service name inside the compose network
  oauth2:
    authorizedRedirectUris:
      - https://dentist.mizhifei.press/oauth2/redirect
      - http://localhost:3000/oauth2/redirect # Default for local React app

# OpenAPI/SpringDoc Configuration - enabled for docker development
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    press.mizhifei.dentist: INFO
    org.springframework: INFO
