server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: true
        # Keep the native configuration for backward compatibility
        native:
          search-locations: classpath:/config

  security:
    user:
      name: ${SPRING_CONFIG_USER}
      password: ${SPRING_CONFIG_PASS}


# Common Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


# Logging Configuration
logging:
  level:
    press.mizhifei.dentist: DEBUG
    org.springframework: DEBUG







