server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zm377/dentistdss-microservices-config
          default-label: main
        # Use the File System Backend to avoid git pulling. Enable "native" profile in the Config Server.
        native:
          searchLocations: file:///${GIT_REPO}
  security:
    user:
      name: ${SPRING_CONFIG_USER}
      password: ${SPRING_CONFIG_PASS}

# Common Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    press.mizhifei.dentist: INFO
    org.springframework.cloud: INFO
    org.springframework.web: INFO 