server:
  port: 8084

spring:
  application:
    name: genai-service
  config:
    import: optional:configserver:http://${SPRING_CONFIG_USER}:${SPRING_CONFIG_PASS}@config-server:8888
  data:
    mongodb:
      uri: mongodb://dentistdss:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/dentistdss?authSource=admin
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano-2025-04-14
    vertex:
      ai:
        gemini:
          project-id: ${VERTEX_AI_PROJECT_ID:}
          location: ${VERTEX_AI_LOCATION:us-central1}
          chat:
            options:
              model: gemini-2.5-pro-20250506

# GenAI Provider Configuration
genai:
  providers:
    default-provider: openai
    switching:
      enable-failover: true
      max-retries: 3
      timeout-ms: 30000
      enable-load-balancing: false
      load-balancing-strategy: round_robin
    openai:
      enabled: true
      default-model: gpt-4.1-nano-2025-04-14
      weight: 50
      max-tokens: 4096
      temperature: 0.7
    vertexai:
      enabled: ${VERTEX_AI_ENABLED:false}
      project-id: ${VERTEX_AI_PROJECT_ID:}
      location: ${VERTEX_AI_LOCATION:us-central1}
      default-model: gemini-2.5-pro-20250506
      weight: 50
      max-tokens: 4096
      temperature: 0.7

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: false

# OpenAPI/SpringDoc Configuration - DISABLED for production

# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info  # Minimal exposure for production
  endpoint:
    health:
      show-details: when-authorized
  jmx:
    exposure:
      exclude: "*"  # Disable JMX to avoid RMI issues
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    press.mizhifei.dentist: INFO
    org.springframework: INFO
    root: INFO
